2024-08-31 19:12:52,343 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Артур\Desktop\test_12_4.py", line 19, in test_run
    runner = Runner(123)
             ^^^^^^^^^^^
  File "C:\Users\Артур\Desktop\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-08-31 19:12:52,346 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\Артур\Desktop\test_12_4.py", line 10, in test_walk
    runner = Runner('Jack', -5)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Артур\Desktop\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
